Modify body-line-height value
Madelena/Metrology-for-Hass pull request #8
Opened 2022-05-14 04:34 UTC by fOmey

This fixes lowercase "g" & "y" characters being cut off.. 

![Capture](https://user-images.githubusercontent.com/5051561/168410765-17b120eb-e044-459f-84b9-764f23a7a0d3.PNG)
![Capture2](https://user-images.githubusercontent.com/5051561/168410768-81adb337-f732-47d0-acc1-7b40a29bffe0.PNG)

2022-05-14 04:55 UTC, fOmey commented
Removed transparency to be more consistent with the other dialog popups.. 

Before:
![Capture3](https://user-images.githubusercontent.com/5051561/168411288-2356fb08-9d31-42bc-9531-79c0de862634.png)

After:
![Capture4](https://user-images.githubusercontent.com/5051561/168411292-b99ef911-d71c-4298-83ce-addf61125ccd.png)

2022-05-14 07:19 UTC, fOmey commented
Modified masonry-view-card-margin, fixes mismatched spacing between panels.

Before:
![Capture5](https://user-images.githubusercontent.com/5051561/168415367-081d24b2-7d48-4cc9-ac85-68cdef9eafad.png)

After:
![Capture6](https://user-images.githubusercontent.com/5051561/168415371-be3b1c81-2d74-4167-8e90-52b182e785ed.png)

2022-05-15 09:59 UTC, Madelena commented
> Removed transparency to be more consistent with the other dialog popups..

I supposed you don't have backdrop-filter turned on? Looks like it's your browser settings?

2022-05-15 10:01 UTC, Madelena requested changes
Is your browser's backdrop-filter blur working?

2022-05-15 10:03 UTC, Madelena requested changes
The theme is set to Segoe UI as the font. And since you aren't using Segoe UI, line-height will certainly clip some of the characters.

2022-05-15 10:03 UTC, Madelena approved these changes

2022-05-15 10:09 UTC, Madelena requested changes
The transparency is necessary for backdrop-filter blur, so probably not.

2022-05-15 10:34 UTC, merged

2022-05-15 10:46 UTC, fOmey commented
> Is your browser's backdrop-filter blur working?

I'm using firefox, supposedly backdrop-filter not merged into mainline firefox.. so that may be the issue.

> The theme is set to Segoe UI as the font. And since you aren't using Segoe UI, line-height will certainly clip some of the characters.

I'm using the default font in firefox (Times new roman).. regardless tho I really think spacing should support various fonts.

2022-05-15 10:51 UTC, Madelena commented
Metro theme is set out to be specifically about the Metro design system, in which the Segoe UI font *is* what Metro is about, so using other fonts will be out of scope unfortunately. Every font has its own line-height quirks and it will be hard to accommodate all of them.

I will check out Firefox and see how to fix that. Thanks for the report.

2022-05-15 11:11 UTC, Madelena commented
@fOmey Ok, I changed body-line-height to set as 'normal', so it should work with other fonts if needed.

2022-05-15 11:57 UTC, fOmey commented
> @fOmey Ok, I changed body-line-height to set as 'normal', so it should work with other fonts if needed. Sorry, my bad. I misunderstood what you meant.
> 
> That was the card from the Minimalist theme, correct? Or is it a button-card?

That's a [slider-button-card](https://github.com/mattieha/slider-button-card).

> Metro theme is set out to be specifically about the Metro design system, in which the Segoe UI font _is_ what Metro is about, so using other fonts will be out of scope unfortunately. Every font has its own line-height quirks and it will be hard to accommodate all of them.
> 
> I will check out Firefox and see how to fix that. Thanks for the report.

Oh I totally get and appreciate that you're trying to replicate the metro UI as close as possible.. I just think most users would be using whatever the default browser font is and expanding the compatibility is in the best interest of the user base.

Can we not force a particular font to render so everyone has the same experience?

2022-05-15 14:37 UTC, Madelena commented
Yeah, I set the font stack to stick with system default (rather than browser default), and I also fixed the line height per your feedback.

2022-05-17 01:15 UTC, Madelena commented
> Modified masonry-view-card-margin, fixes mismatched spacing between panels.
> 
> Before: ![Capture5](https://user-images.githubusercontent.com/5051561/168415367-081d24b2-7d48-4cc9-ac85-68cdef9eafad.png)
> 
> After: ![Capture6](https://user-images.githubusercontent.com/5051561/168415371-be3b1c81-2d74-4167-8e90-52b182e785ed.png)

I just realized this fix actually ended up mismatching everything else. Is it an issue that happens just between light entity cards and other cards?

2022-05-17 01:22 UTC, Madelena commented
> Modified masonry-view-card-margin, fixes mismatched spacing between panels.
> 
> Before: ![Capture5](https://user-images.githubusercontent.com/5051561/168415367-081d24b2-7d48-4cc9-ac85-68cdef9eafad.png)
> 
> After: ![Capture6](https://user-images.githubusercontent.com/5051561/168415371-be3b1c81-2d74-4167-8e90-52b182e785ed.png)

Can you paste your card config here? I realized that changing the masonry margin affects everything else and made margins on my config mismatched.

2022-05-17 02:19 UTC, Madelena commented
Nevermind. Turns out to be a bug in layout-card https://github.com/thomasloven/lovelace-layout-card/issues/194